FROM node:20

WORKDIR /usr/src/nestar

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build the application
RUN npm run build nestar-batch

# Expose port
EXPOSE 3006

# Start the application
CMD ["node", "dist/apps/nestar-batch/main.js"]
